name: Deploy AWS CDK .NET App

on:
  push:
    branches:
      - staging  # ✅ Deploy to staging first
      - main     # ✅ Deploy to production only if staging succeeds

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Get AWS Account ID
        run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Restore Dependencies
        run: dotnet restore src/Project1/

      - name: Run Unit Tests  # ✅ Ensure staging is working before deploying
        run: dotnet test src/Project1.Tests/ --configuration Release --logger trx || exit 1

      - name: Build Application
        run: dotnet build src/Project1/ --configuration Release

      - name: Bootstrap AWS Environment (if not already bootstrapped)
        run: cdk bootstrap aws://$AWS_ACCOUNT_ID/ap-south-1
        env:
          AWS_REGION: ap-south-1

      - name: Synthesize AWS CDK Stack
        run: cdk synth

      - name: Deploy to Staging
        id: deploy_staging
        if: github.ref == 'refs/heads/staging'
        run: cdk deploy --require-approval never
        env:
          AWS_REGION: ap-south-1

      - name: Rollback Staging on Failure
        if: failure() && github.ref == 'refs/heads/staging'
        run: cdk destroy -f
        env:
          AWS_REGION: ap-south-1

      - name: Deploy to Production (Only if staging is successful)
        id: deploy_production
        if: github.ref == 'refs/heads/main'
        run: cdk deploy --require-approval never
        env:
          AWS_REGION: ap-south-1

      - name: Rollback Production on Failure
        if: failure() && github.ref == 'refs/heads/main'
        run: |
          echo "⚠️ Deployment failed! Rolling back to previous stable version..."
          git revert HEAD --no-edit
          git push origin main
        env:
          AWS_REGION: ap-south-1
